social/urls.py
from django.urls import path
from . import views

app_name = 'social'
urlpatterns = [
    path('', views.profile, name='profile'),
    path('register/', views.user_register, name='register'),
    path('user/edit/', views.user_edit, name='user_edit'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('ticket/', views.ticket, name='ticket'),
    path('password_change/', views.CustomPasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.CustomPasswordChangeDoneView.as_view(), name='password_change_done'),
    path('reset_password/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('reset_password/done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset_password/confirm/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password/complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('post/list/', views.post_list, name='post_list'),
    path('post/list/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('post/detail/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post/create/', views.post_create, name='post_create'),
    path('post/comment/<int:post_id>/', views.post_comment, name='post_comment'),
    path('search/', views.post_search, name='post_search'),
    path('like_post/', views.like_post, name='like_post'),
    path('save_post/', views.save_post, name='save_post'),
    path('user/list/', views.user_list, name='user_list'),
    path('user/detail/<str:username>/', views.user_detail, name='user_detail'),
    path('user/follow/', views.user_follow, name='user_follow'),
    path('user/<str:username>/<str:rel>/', views.contact, name='user_contact'),
]

social_network_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social.urls', namespace='social')),
    path("__debug__/", include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/forms.py
from django import forms
from .models import User, Post, Comment


class LoginForm(forms.Form):
    username = forms.CharField(max_length=200, required=True, label="نام کاربری یا تلفن", widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=200, required=True, label="رمز عبور", widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegisterForm(forms.ModelForm):
    password1 = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='پسورد')
    password2 = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='تکرار پسورد')

    class Meta:
        model = User
        fields = ['username', 'phone', 'first_name', 'last_name']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'username': 'نام کاربری',
            'first_name': 'نام',
            'last_name': 'نام خانوادگی',
            'phone': 'شماره تماس',
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('پسورد ها مطابقت ندارند')
        return cd['password2']

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("این نام کاربری وجود دارد")
        return username

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if User.objects.filter(phone=phone).exists():
            raise forms.ValidationError("این شماره تلفن وجود دارد")
        return phone


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'phone', 'date_of_birth', 'bio', 'photo', 'job']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'date_of_birth': forms.DateInput(attrs={'class': 'form-control'}),
            'bio': forms.TextInput(attrs={'class': 'form-control'}),
            'photo': forms.FileInput(attrs={'class': 'form-control'}),
            'job': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'username': 'نام کاربری',
            'first_name': 'نام',
            'last_name': 'نام خانوادگی',
            'email': 'ایمیل',
            'date_of_birth': 'تاریخ تولد',
            'phone': 'شماره تماس',
            'bio': 'بایو',
            'job': 'شغل',
        }

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.exclude(id=self.instance.id).filter(username=username).exists():
            raise forms.ValidationError("نام کاربری وجود دارد")
        return username

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if User.objects.exclude(id=self.instance.id).filter(phone=phone).exists():
            raise forms.ValidationError("شماره تلفن وجود دارد")
        return phone


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش'),
    )
    name = forms.CharField(max_length=100, required=True, label='نام', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(max_length=100, required=True, label='ایمیل', widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone = forms.CharField(max_length=11, required=True, label='شماره تماس', widget=forms.TextInput(attrs={'class': 'form-control'}))
    message = forms.CharField(max_length=500, required=True, label='پیام', widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}))
    subject = forms.ChoiceField(label='موضوع', choices=SUBJECT_CHOICES)

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError("شماره تلفن عددی نیست")
            else:
                return phone


class CreatePostForm(forms.ModelForm):
    image1 = forms.ImageField(label="تصویر اول", widget=forms.FileInput(attrs={'class': 'form-control'}))
    image2 = forms.ImageField(label="تصویر دوم", widget=forms.FileInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Post
        fields = ['description', 'tags']
        widgets = {
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
        }
        labels = {
            'tags': 'تگ ها',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        widgets = {
            'body': forms.TextInput(attrs={'placeholder': 'کامنت بزارید...', 'class': 'form-control input-sm'}),
        }


class SearchForm(forms.Form):
    query = forms.CharField()

social/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (PasswordChangeView, PasswordChangeDoneView, PasswordResetView,
                                       PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView)
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count, Q
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from taggit.models import Tag
from .forms import *
from .models import Post, Contact, Image


def profile(request):
    try:
        user = User.objects.prefetch_related('followers', 'following').get(id=request.user.id)
    except:
        return redirect('social:login')
    saved_posts = user.saved_posts.all()[:7]
    my_posts = user.user_posts.all()[:8]
    following = user.get_followings()
    followers = user.get_followers()
    conntext = {
        'saved_posts': saved_posts,
        'my_posts': my_posts,
        'user': user,
        'following': following,
        'followers': followers,
        'form': CommentForm()
    }
    return render(request, 'social/profile.html', conntext)


def user_register(request):
    if request.user.is_authenticated:
        return redirect('social:profile')
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            messages.success(request, 'با موفقیت ثبت نام کردی', 'success')
            return redirect('social:profile')
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required
def user_edit(request):
    if request.method == 'POST':
        form = UserEditForm(data=request.POST, files=request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('social:profile')
    else:
        form = UserEditForm(instance=request.user)
    return render(request, 'registration/edit_user.html', {'form': form})


def user_login(request):
    if request.user.is_authenticated:
        return redirect('social:profile')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.success(request, 'با موفقیت لاگین شدی', 'success')
                    return redirect('social:profile')
                else:
                    messages.error(request, 'این کاربر فعال نیست', 'danger')
                    return redirect('social:login')
            else:
                messages.error(request, 'نام کاربری یا رمز عبور اشتباه هست', 'danger')
                return redirect('social:login')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})


@login_required
def user_logout(request):
    if request.method == 'POST':
        logout(request)
        return redirect('social:profile')
    return render(request, 'registration/logged_out.html')


@login_required
def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            message = f"{cd['name']}\n{cd['email']}\n{cd['phone']}\n\n{cd['message']}"
            send_mail(cd['subject'], message, 'danielsadri01@gmail.com', ['danielsadri01@gmail.com'], False)
            messages.success(request, 'پیام شما به پشتبانی ارسال شد', 'success')
            return redirect('social:profile')
    else:
        form = TicketForm()
    return render(request, 'forms/ticket.html', {'form': form})


class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'registration/password_change_form.html'
    success_url = reverse_lazy('social:password_change_done')


class CustomPasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'registration/password_change_done.html'


class CustomPasswordResetView(PasswordResetView):
    template_name = 'registration/password_reset_form.html'
    email_template_name = 'registration/password_reset_email.html'
    success_url = reverse_lazy('social:password_reset_done')


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'registration/password_reset_done.html'


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'registration/password_reset_confirm.html'
    success_url = reverse_lazy('social:password_reset_complete')


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'registration/password_reset_complete.html'


def post_list(request, tag_slug=None):
    posts = Post.objects.select_related('author').order_by('-total_likes')
    latest_users = User.objects.filter(is_active=True).order_by('-date_joined')[:4]
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = Post.objects.filter(tags__in=[tag])
    page = request.GET.get('page')
    paginator = Paginator(posts, 2)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = []
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return render(request, 'social/list_ajax.html', {'posts': posts})
    context = {
        'posts': posts,
        'tag': tag,
        'latest_users': latest_users,
    }
    return render(request, "social/list.html", context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_post = Post.objects.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_post = similar_post.annotate(same_tags=Count('tags')).order_by('-same_tags', '-created')[:4]
    context = {
        'post': post,
        'similar_post': similar_post,
        'form': CommentForm()
    }
    return render(request, "social/detail.html", context)


@login_required
def post_create(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            form.save_m2m()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('social:profile')
    else:
        form = CreatePostForm()
    return render(request, 'forms/create-post.html', {'form': form})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.name = request.user.first_name
        comment.save()
    return redirect('social:profile')


def post_search(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data.get('query')
            results = Post.objects.filter(Q(description__icontains=query))
    context = {
        'results': results,
        'query': query
    }
    return render(request, 'social/search.html', context)


@login_required
@require_POST
def like_post(request):
    post_id = request.POST.get('post_id')
    if post_id is not None:
        post = get_object_or_404(Post, id=post_id)
        user = request.user
        if user in post.likes.all():
            post.likes.remove(user)
            liked = False
        else:
            post.likes.add(user)
            liked = True
        post_likes_count = post.likes.count()
        response_data = {'liked': liked, 'likes_count': post_likes_count}
    else:
        response_data = {'error': 'Invalid post_id'}
    return JsonResponse(response_data)


@login_required
@require_POST
def save_post(request):
    post_id = request.POST.get('post_id')
    if post_id is not None:
        post = get_object_or_404(Post, id=post_id)
        user = request.user
        if user in post.saved_by.all():
            post.saved_by.remove(user)
            saved = False
        else:
            post.saved_by.add(user)
            saved = True
        response_data = {'saved': saved}
    else:
        response_data = {'error': 'Invalid request'}
    return JsonResponse(response_data)


@login_required
def user_list(request):
    users = User.objects.filter(is_active=True)
    return render(request, 'user/user_list.html', {'users': users})


@login_required
def user_detail(request, username):
    user = get_object_or_404(User, username=username, is_active=True)
    return render(request, 'user/user_detail.html', {'user': user})


@login_required
@require_POST
def user_follow(request):
    user_id = request.POST.get('id')
    if user_id:
        try:
            user = User.objects.get(id=user_id)
            if request.user in user.followers.all():
                Contact.objects.filter(user_from=request.user, user_to=user).delete()
                follow = False
            else:
                Contact.objects.get_or_create(user_from=request.user, user_to=user)
                follow = True
            following_count = user.following.count()
            followers_count = user.followers.count()

social/templates/partials/footer_references.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>

social/templates/partials/header.html
{% load static %}
<header class="tr-header">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-left col-md-5">
                <ul class="nav navbar-nav">
                    <li>
                        <div class="search-dashboard">
                            <form action="{% url 'social:post_search' %}" method="get" novalidate>
                                <input type="text" name="query" placeholder="جستجو کنید...">
                                <button type="submit"><i class="fa fa-search"></i></button>
                            </form>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="navbar-header col-md-5">
                <div class="dropdown mega-avatar">
                    <a style="text-decoration: none" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                        {% if request.user.photo %}
                            <span class="avatar w-32">
                                <img src="{{ request.user.photo.url }}" class="img-resonsive img-circle" width="25" height="25" alt="...">
                            </span>
                        {% else %}
                            <span class="avatar w-32">
                                <img src="{% static 'images/profile/Avatar.png' %}" class="img-resonsive img-circle" width="25" height="25" alt="...">
                            </span>
                        {% endif %}
                    </a>
                    <div class="dropdown-menu w dropdown-menu-scale pull-right">
                        <a class="dropdown-item" href="{% url 'social:post_create' %}"><span>پست جدید</span></a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'social:profile' %}"><span>پروفایل</span></a>
                        <a class="dropdown-item" href="{% url 'social:user_edit' %}"><span>تنظیمات</span></a>
                        <a class="dropdown-item" href="{% url 'social:ticket' %}">پشتیبانی</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'social:logout' %}">خروج</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>

social/templates/partials/header_references.html
{% load static %}
<link rel="icon" href="{% static 'img/logo.html' %}">
<link rel="apple-touch-icon" href="{% static 'img/favicons/apple-touch-icon.html' %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/favicons/apple-touch-icon-72x72.html' %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/favicons/apple-touch-icon-114x114.html' %}">
<link type="text/css" href="{% static 'css/demos/photo.css' %}" rel="stylesheet"/>
<link type="text/css" href="{% static 'css/font.css' %}" rel="stylesheet"/>
<script src="{% static 'js/modernizr-custom.html' %}"></script>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

social/templates/partials/messages.html
{% if messages %}
    {% for message in messages %}
        <p class="alert alert-{{ message.tags }}">{{ message }}</p>
    {% endfor %}
{% endif %}

social/templates/partials/my-modal.html
{% load static %}
<div id="myModal-{{ post_id }}" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-8 modal-image">
                        <img class="img-responsive" src="{{ my_post.images.first.image_file.url }}" alt="Image"/>
                        <br>
                        <div class="text-center"><p class="text-dark">{{ my_post.description }}</p></div>
                        <br>
                        <div class="text-center">
                            {% for tag in my_post.tags.all %}
                                <a class="text-dark" href="{% url 'social:post_list_by_tag' tag.slug %}">
                                    <button> {{ tag.name }}</button>
                                </a>
                                {% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    <br>
                    <!--/ col-md-8 -->
                    <div class="col-md-4 modal-meta">
                        <div class="modal-meta-top">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                <span aria-hidden="true">×</span><span class="sr-only">بستن</span>
                            </button>
                            <div class="img-poster clearfix">
                                <a href="#"><img class="img-responsive img-circle" src="{{ user.photo.url }}"
                                                 alt="Image"/></a>
                                <strong><a href="#">{{ user.get_full_name }}</a></strong>
                            </div>
                            <ul class="img-comment-list">
                                {% for comment in my_post.comments.all %}
                                    <li>
                                        <div class="comment-img">
                                            <img src="{% static 'images/profile/avatar2.png' %}" class="img-responsive img-circle" alt="Image"/>
                                        </div>
                                        <div class="comment-text">
                                            <strong><a href="#">{{ comment.name }}</a></strong>
                                            <p class="">{{ comment.body }}</p> <span class="date sub-text"> در {{ comment.created }} </span>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                            <div class="modal-meta-bottom">
                                <ul>
                                    <li><a class="modal-like" href="#"><i class="fa fa-heart"></i></a><span class="modal-one"> {{ my_post.total_likes }}</span> |
                                        <a class="modal-comment" href="#"><i class="fa fa-comments"></i></a><span>{{ my_post.comments.count }}</span>
                                    </li>
                                    <li>
										<span class="thumb-xs"><img class="img-responsive img-circle" src="{% static 'images/profile/avatar2.webp' %}" alt="Image"></span>
                                        <div class="comment-body">
                                            <form method="post" action="{% url 'social:post_comment' my_post.id %}">
                                                {% csrf_token %}
                                                {{ form.as_div }}
                                                <div class="col-12"><button type="submit" class="btn btn-dark">ثبت</button></div>
                                            </form>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

social/templates/partials/navigation.html
<section class="nav-sec">
    <div class="d-flex justify-content-between">
        <div class="p-2 nav-icon-lg dark-black">
            <a class="nav-icon" href="{% url 'social:post_list' %}"><em class="fa fa-home"></em><span>خانه</span></a>
        </div>
        <div class="p-2 nav-icon-lg clean-black">
            <a class="nav-icon" href="{% url 'social:post_list' %}"><em class="fa fa-list-ul"></em><span>پیام</span></a>
        </div>
        <div class="p-2 nav-icon-lg dark-black">
            <a class="nav-icon" href="{% url 'social:post_create' %}"><em class="fab fa-instagram"></em><span>ایجاد پست</span></a>
        </div>
        <div class="p-2 nav-icon-lg clean-black">
            <a class="nav-icon" href="{% url 'social:user_list' %}"><em class="fa fa-align-left"></em><span>کاربران</span></a>
        </div>
        <div class="p-2 nav-icon-lg mint-green">
            <a class="nav-icon" href="{% url 'social:profile' %}"><em class="fa fa-user"></em><span>پروفایل</span></a>
        </div>
    </div>
</section>