social/urls.py
from django.urls import path
from . import views

app_name = 'social'
urlpatterns = [
    path('', views.profile, name='profile'),
    path('register/', views.user_register, name='register'),
    path('user/edit/', views.user_edit, name='user_edit'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('ticket/', views.ticket, name='ticket'),
    path('password_change/', views.CustomPasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.CustomPasswordChangeDoneView.as_view(), name='password_change_done'),
    path('reset_password/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('reset_password/done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset_password/confirm/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password/complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('post/list/', views.post_list, name='post_list'),
    path('post/list/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('post/detail/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post/create/', views.post_create, name='post_create'),
    path('post/comment/<int:post_id>/', views.post_comment, name='post_comment'),
    path('search/', views.post_search, name='post_search'),
    path('like_post/', views.like_post, name='like_post'),
    path('save_post/', views.save_post, name='save_post'),
    path('user/list/', views.user_list, name='user_list'),
    path('user/detail/<str:username>/', views.user_detail, name='user_detail'),
    path('user/follow/', views.user_follow, name='user_follow'),
    path('user/<str:username>/<str:rel>/', views.contact, name='user_contact'),
]

social_network_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social.urls', namespace='social')),
    path("__debug__/", include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/forms.py
from django import forms
from .models import User, Post, Comment


class LoginForm(forms.Form):
    username = forms.CharField(max_length=200, required=True, label="نام کاربری یا تلفن", widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=200, required=True, label="رمز عبور", widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegisterForm(forms.ModelForm):
    password1 = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='پسورد')
    password2 = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='تکرار پسورد')

    class Meta:
        model = User
        fields = ['username', 'phone', 'first_name', 'last_name']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'username': 'نام کاربری',
            'first_name': 'نام',
            'last_name': 'نام خانوادگی',
            'phone': 'شماره تماس',
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('پسورد ها مطابقت ندارند')
        return cd['password2']

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("این نام کاربری وجود دارد")
        return username

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if User.objects.filter(phone=phone).exists():
            raise forms.ValidationError("این شماره تلفن وجود دارد")
        return phone


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'phone', 'date_of_birth', 'bio', 'photo', 'job']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'date_of_birth': forms.DateInput(attrs={'class': 'form-control'}),
            'bio': forms.TextInput(attrs={'class': 'form-control'}),
            'photo': forms.FileInput(attrs={'class': 'form-control'}),
            'job': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'username': 'نام کاربری',
            'first_name': 'نام',
            'last_name': 'نام خانوادگی',
            'email': 'ایمیل',
            'date_of_birth': 'تاریخ تولد',
            'phone': 'شماره تماس',
            'bio': 'بایو',
            'job': 'شغل',
        }

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.exclude(id=self.instance.id).filter(username=username).exists():
            raise forms.ValidationError("نام کاربری وجود دارد")
        return username

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if User.objects.exclude(id=self.instance.id).filter(phone=phone).exists():
            raise forms.ValidationError("شماره تلفن وجود دارد")
        return phone


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش'),
    )
    name = forms.CharField(max_length=100, required=True, label='نام', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(max_length=100, required=True, label='ایمیل', widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone = forms.CharField(max_length=11, required=True, label='شماره تماس', widget=forms.TextInput(attrs={'class': 'form-control'}))
    message = forms.CharField(max_length=500, required=True, label='پیام', widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}))
    subject = forms.ChoiceField(label='موضوع', choices=SUBJECT_CHOICES)

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError("شماره تلفن عددی نیست")
            else:
                return phone


class CreatePostForm(forms.ModelForm):
    image1 = forms.ImageField(label="تصویر اول", widget=forms.FileInput(attrs={'class': 'form-control'}))
    image2 = forms.ImageField(label="تصویر دوم", widget=forms.FileInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Post
        fields = ['description', 'tags']
        widgets = {
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
        }
        labels = {
            'tags': 'تگ ها',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        widgets = {
            'body': forms.TextInput(attrs={'placeholder': 'کامنت بزارید...', 'class': 'form-control input-sm'}),
        }


class SearchForm(forms.Form):
    query = forms.CharField()

social/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (PasswordChangeView, PasswordChangeDoneView, PasswordResetView,
                                       PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView)
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count, Q
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from taggit.models import Tag
from .forms import *
from .models import Post, Contact, Image


def profile(request):
    try:
        user = User.objects.prefetch_related('followers', 'following').get(id=request.user.id)
    except:
        return redirect('social:login')
    saved_posts = user.saved_posts.all()[:7]
    my_posts = user.user_posts.all()[:8]
    following = user.get_followings()
    followers = user.get_followers()
    conntext = {
        'saved_posts': saved_posts,
        'my_posts': my_posts,
        'user': user,
        'following': following,
        'followers': followers,
        'form': CommentForm()
    }
    return render(request, 'social/profile.html', conntext)


def user_register(request):
    if request.user.is_authenticated:
        return redirect('social:profile')
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            messages.success(request, 'با موفقیت ثبت نام کردی', 'success')
            return redirect('social:profile')
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required
def user_edit(request):
    if request.method == 'POST':
        form = UserEditForm(data=request.POST, files=request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('social:profile')
    else:
        form = UserEditForm(instance=request.user)
    return render(request, 'registration/edit_user.html', {'form': form})


def user_login(request):
    if request.user.is_authenticated:
        return redirect('social:profile')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.success(request, 'با موفقیت لاگین شدی', 'success')
                    return redirect('social:profile')
                else:
                    messages.error(request, 'این کاربر فعال نیست', 'danger')
                    return redirect('social:login')
            else:
                messages.error(request, 'نام کاربری یا رمز عبور اشتباه هست', 'danger')
                return redirect('social:login')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})


@login_required
def user_logout(request):
    if request.method == 'POST':
        logout(request)
        return redirect('social:profile')
    return render(request, 'registration/logged_out.html')


@login_required
def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            message = f"{cd['name']}\n{cd['email']}\n{cd['phone']}\n\n{cd['message']}"
            send_mail(cd['subject'], message, 'danielsadri01@gmail.com', ['danielsadri01@gmail.com'], False)
            messages.success(request, 'پیام شما به پشتبانی ارسال شد', 'success')
            return redirect('social:profile')
    else:
        form = TicketForm()
    return render(request, 'forms/ticket.html', {'form': form})


class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'registration/password_change_form.html'
    success_url = reverse_lazy('social:password_change_done')


class CustomPasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'registration/password_change_done.html'


class CustomPasswordResetView(PasswordResetView):
    template_name = 'registration/password_reset_form.html'
    email_template_name = 'registration/password_reset_email.html'
    success_url = reverse_lazy('social:password_reset_done')


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'registration/password_reset_done.html'


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'registration/password_reset_confirm.html'
    success_url = reverse_lazy('social:password_reset_complete')


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'registration/password_reset_complete.html'


def post_list(request, tag_slug=None):
    posts = Post.objects.select_related('author').order_by('-total_likes')
    latest_users = User.objects.filter(is_active=True).order_by('-date_joined')[:4]
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = Post.objects.filter(tags__in=[tag])
    page = request.GET.get('page')
    paginator = Paginator(posts, 2)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = []
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return render(request, 'social/list_ajax.html', {'posts': posts})
    context = {
        'posts': posts,
        'tag': tag,
        'latest_users': latest_users,
    }
    return render(request, "social/list.html", context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_post = Post.objects.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_post = similar_post.annotate(same_tags=Count('tags')).order_by('-same_tags', '-created')[:4]
    context = {
        'post': post,
        'similar_post': similar_post,
        'form': CommentForm()
    }
    return render(request, "social/detail.html", context)


@login_required
def post_create(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            form.save_m2m()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('social:profile')
    else:
        form = CreatePostForm()
    return render(request, 'forms/create-post.html', {'form': form})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.name = request.user.first_name
        comment.save()
    return redirect('social:profile')


def post_search(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data.get('query')
            results = Post.objects.filter(Q(description__icontains=query))
    context = {
        'results': results,
        'query': query
    }
    return render(request, 'social/search.html', context)


@login_required
@require_POST
def like_post(request):
    post_id = request.POST.get('post_id')
    if post_id is not None:
        post = get_object_or_404(Post, id=post_id)
        user = request.user
        if user in post.likes.all():
            post.likes.remove(user)
            liked = False
        else:
            post.likes.add(user)
            liked = True
        post_likes_count = post.likes.count()
        response_data = {'liked': liked, 'likes_count': post_likes_count}
    else:
        response_data = {'error': 'Invalid post_id'}
    return JsonResponse(response_data)


@login_required
@require_POST
def save_post(request):
    post_id = request.POST.get('post_id')
    if post_id is not None:
        post = get_object_or_404(Post, id=post_id)
        user = request.user
        if user in post.saved_by.all():
            post.saved_by.remove(user)
            saved = False
        else:
            post.saved_by.add(user)
            saved = True
        response_data = {'saved': saved}
    else:
        response_data = {'error': 'Invalid request'}
    return JsonResponse(response_data)


@login_required
def user_list(request):
    users = User.objects.filter(is_active=True)
    return render(request, 'user/user_list.html', {'users': users})


@login_required
def user_detail(request, username):
    user = get_object_or_404(User, username=username, is_active=True)
    return render(request, 'user/user_detail.html', {'user': user})


@login_required
@require_POST
def user_follow(request):
    user_id = request.POST.get('id')
    if user_id:
        try:
            user = User.objects.get(id=user_id)
            if request.user in user.followers.all():
                Contact.objects.filter(user_from=request.user, user_to=user).delete()
                follow = False
            else:
                Contact.objects.get_or_create(user_from=request.user, user_to=user)
                follow = True
            following_count = user.following.count()
            followers_count = user.followers.count()

social/templates/user/user_detail.html
{% extends 'parent/base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %} profile {% endblock %}

{% block content %}
    <section class="profile">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-3">
                    <div class="profilebox hidden-xs hidden-sm"
                         style="background: linear-gradient( rgba(34,34,34,0.45), rgba(34,34,34,0.45)), url('{% static 'img/posts/4.jpg' %}') no-repeat;
                                 background-size: cover;
                                 background-position: center center;
                                 -webkit-background-size: cover;
                                 -moz-background-size: cover;
                                 -o-background-size: cover;">
                    </div>
                    <div class="profilebox hidden-xs hidden-sm"
                         style="background: linear-gradient( rgba(34,34,34,0.45), rgba(34,34,34,0.45)), url('{% static 'img/posts/1.jpg' %}') no-repeat;
                                 background-size: cover;
                                 background-position: center center;
                                 -webkit-background-size: cover;
                                 -moz-background-size: cover;
                                 -o-background-size: cover;">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="profilebox-large hidden-xs hidden-sm"
                         style="background: linear-gradient( rgba(34,34,34,0.45), rgba(34,34,34,0.45)), url('{% static 'img/posts/9.jpg' %}') no-repeat;
                                 background-size: cover;
                                 background-position: center center;
                                 -webkit-background-size: cover;
                                 -moz-background-size: cover;
                                 -o-background-size: cover;">
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="profilebox hidden-xs hidden-sm"
                         style="background: linear-gradient( rgba(34,34,34,0.45), rgba(34,34,34,0.45)), url('{% static 'img/posts/11.jpg' %}') no-repeat;
                                 background-size: cover;
                                 background-position: center center;
                                 -webkit-background-size: cover;
                                 -moz-background-size: cover;
                                 -o-background-size: cover;">
                    </div>
                    <div class="profilebox"
                         style="background: linear-gradient( rgba(34,34,34,0.6), rgba(34,34,34,0.6)), url('{% static 'img/posts/12.jpg' %}') no-repeat;
                                 background-size: cover;
                                 background-position: center center;
                                 -webkit-background-size: cover;
                                 -moz-background-size: cover;
                                 -o-background-size: cover;">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="user-profile">
        <div class="container-fluid">
            <div class="row">

                <div class="col-lg-12">
                    <div class="post-content">
                        <div class="author-post text-center">
                            <a href="#"><img class="img-fluid img-circle" src="{{ user.photo.url }}" alt="Image"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="details">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="details-box row">
                        <div class="col-lg-9">
                            <div class="content-box">
                                <h4>{{ user.get_full_name }} <i class="fa fa-check"></i></h4>
                                <p>{{ user.bio |default:"این کاربر بایو ندارد." }}</p>
                                <p>{{ user.job |default:"این کاربر شغلی ندارد." }}</p>
                                <small><span>{{ user.username }}</span></small>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            {% if request.user == user %}
                            {% else %}
                                {% if request.user in user.followers.all %}
                                    <button class="kafe-btn kafe-btn-danger" id="follow-button"> آنفالو</button>
                                {% else %}
                                    <button class="kafe-btn kafe-btn-mint" id="follow-button"> فالو</button>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="home-menu">
        <div class="container">
            <div class="row">
                <div class="menu-category">
                    {% with total_followers=user.followers.count total_following=user.following.count total_post=user.user_posts.count %}
                        <ul class="menu">
                            <li class="current-menu-item">
                                <a style="text-decoration: none">
                                    پست&nbsp;<span>&nbsp;{{ total_post }}&nbsp;</span>
                                </a>
                            </li>
                            <li>
                                <a style="text-decoration: none">
                                    دنبال کننده&nbsp; <span class="followers-count">&nbsp;{{ total_followers }}&nbsp;</span>
                                </a>
                            </li>
                            <li>
                                <a style="text-decoration: none">
                                    نفر را دنبال می کند&nbsp;<span class="following-count">&nbsp;{{ total_following }}&nbsp;</span>
                                </a>
                            </li>
                        </ul>
                    {% endwith %}
                </div>
            </div>
        </div>
    </section>
    <section class="newsfeed">
        <div class="container">
            <div class="row">
                {% for post in user.user_posts.all %}
                    <div class="col-lg-4">
                        <a href="{% url 'social:post_detail' post.id %}" data-toggle="modal">
                            <div class="explorebox" style="background: linear-gradient( rgba(34,34,34,0.2), rgba(34,34,34,0.2)), url('{{ post.images.first.image_file.url }}') no-repeat;
                                         background-size: cover;
                                         background-position: center center;
                                         -webkit-background-size: cover;
                                         -moz-background-size: cover;
                                         -o-background-size: cover;">
                                <div class="explore-top">
                                    <div class="explore-like"><i
                                            class="fa fa-heart"></i><span>{{ post.total_likes }}</span></div>
                                    <div class="explore-circle pull-left">
                                        <span>{{ post.total_saves }}</span><i class="far fa-bookmark"></i></div>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>
    <script src="{% static 'plugins/slimscroll/jquery.slimscroll.js' %}"></script>
    <script>
        $('#Slim,#Slim2').slimScroll({
            height: "auto",
            position: 'right',
            railVisible: true,
            alwaysVisible: true,
            size: "8px",
        });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
            integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        $(document).ready(function () {
            $('#follow-button').click(function () {
                var button = $(this);
                $.ajax({
                    type: 'POST',
                    url: '{% url 'social:user_follow' %}',
                    data: {'id': '{{user.id}}', 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                    success: function (data) {
                        if (data.follow) {
                            button.removeClass('kafe-btn-mint');
                            button.addClass('kafe-btn-danger');
                            button.text('آنفالو');
                        } else {
                            button.removeClass('kafe-btn-danger');
                            button.addClass('kafe-btn-mint');
                            button.text('فالو');
                        }
                        $('.followers-count').text('  ' + data.followers_count + '  ');
                        $('.following-count').text('  ' + data.following_count + '  ');
                    },
                });
            });
        });
    </script>
{% endblock %}

social/templates/user/user_list.html
{% extends 'parent/base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %} users list {% endblock %}

{% block content %}
    <section class="followers">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="followers-box full-width">
                        <div class="followers-list">
                            {% for user in users %}
                                <div class="followers-body">
                                    <a href="{% url 'social:user_detail' user.username %}">
                                        <img class="img-responsive img-circle" src="{{ user.photo.url }}" alt="">
                                    </a>
                                    <div class="name-box">
                                        <h4>{{ user.get_full_name }}</h4>
                                        <span>{{ user.username }}</span>
                                        <div class="followers-base">
                                            <ul class="list-group">
                                                <li class="list-group-item full-width">
                                                    <div class="pull-right" style="margin-left: 20px;">
                                                        {% for follower in user.followers.all|slice:"0:4" %}
                                                            <img src="{{ follower.photo.url }}" alt="" class="img-circle max-w-40 ">
                                                        {% endfor %}
                                                        <a href="{% url 'social:user_contact' user.username 'followers' %}">
                                                            <button class="btn btn-add-gray"><i class="fa fa-plus"></i></button>
                                                        </a>
                                                        <span> {{ user.followers.count }} دنبال کننده </span>
                                                    </div>
                                                </li>
                                                <li class="list-group-item full-width">
                                                    <div class="pull-right">
                                                        {% for following in user.following.all|slice:"0:4" %}
                                                            <img src="{{ following.photo.url }}" alt="" class="img-circle max-w-40 ">
                                                        {% endfor %}
                                                        <a href="{% url 'social:user_contact' user.username 'following' %}">
                                                            <button class="btn btn-add-gray"><i class="fa fa-plus"></i></button>
                                                        </a>
                                                        <span> {{ user.following.count }} نفر را دنبال می کند</span>
                                                    </div>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <span><a href="#" style="text-decoration: none"  class="kafe-btn kafe-btn-mint-small">دنبال کردن</a></span>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>
    <script src="{% static 'plugins/slimscroll/jquery.slimscroll.js' %}"></script>
    <script>
        $('#Slim,#Slim2').slimScroll({
            height: "auto",
            position: 'right',
            railVisible: true,
            alwaysVisible: true,
            size: "8px",
        });
    </script>
{% endblock %}