social/urls.py
from django.urls import path
from . import views

app_name = 'social'
urlpatterns = [
    path('', views.profile, name='profile'),
    path('register/', views.user_register, name='register'),
    path('user/edit/', views.user_edit, name='user_edit'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('ticket/', views.ticket, name='ticket'),
    path('password_change/', views.CustomPasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.CustomPasswordChangeDoneView.as_view(), name='password_change_done'),
    path('reset_password/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('reset_password/done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset_password/confirm/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password/complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('post/list/', views.post_list, name='post_list'),
    path('post/list/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('post/detail/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post/create/', views.post_create, name='post_create'),
    path('post/comment/<int:post_id>/', views.post_comment, name='post_comment'),
    path('search/', views.post_search, name='post_search'),
    path('like_post/', views.like_post, name='like_post'),
    path('save_post/', views.save_post, name='save_post'),
    path('user/list/', views.user_list, name='user_list'),
    path('user/detail/<str:username>/', views.user_detail, name='user_detail'),
    path('user/follow/', views.user_follow, name='user_follow'),
    path('user/<str:username>/<str:rel>/', views.contact, name='user_contact'),
]

social_network_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social.urls', namespace='social')),
    path("__debug__/", include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/forms.py
from django import forms
from .models import User, Post, Comment


class LoginForm(forms.Form):
    username = forms.CharField(max_length=200, required=True, label="نام کاربری یا تلفن", widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=200, required=True, label="رمز عبور", widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegisterForm(forms.ModelForm):
    password1 = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='پسورد')
    password2 = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='تکرار پسورد')

    class Meta:
        model = User
        fields = ['username', 'phone', 'first_name', 'last_name']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'username': 'نام کاربری',
            'first_name': 'نام',
            'last_name': 'نام خانوادگی',
            'phone': 'شماره تماس',
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('پسورد ها مطابقت ندارند')
        return cd['password2']

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("این نام کاربری وجود دارد")
        return username

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if User.objects.filter(phone=phone).exists():
            raise forms.ValidationError("این شماره تلفن وجود دارد")
        return phone


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'phone', 'date_of_birth', 'bio', 'photo', 'job']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'date_of_birth': forms.DateInput(attrs={'class': 'form-control'}),
            'bio': forms.TextInput(attrs={'class': 'form-control'}),
            'photo': forms.FileInput(attrs={'class': 'form-control'}),
            'job': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'username': 'نام کاربری',
            'first_name': 'نام',
            'last_name': 'نام خانوادگی',
            'email': 'ایمیل',
            'date_of_birth': 'تاریخ تولد',
            'phone': 'شماره تماس',
            'bio': 'بایو',
            'job': 'شغل',
        }

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.exclude(id=self.instance.id).filter(username=username).exists():
            raise forms.ValidationError("نام کاربری وجود دارد")
        return username

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if User.objects.exclude(id=self.instance.id).filter(phone=phone).exists():
            raise forms.ValidationError("شماره تلفن وجود دارد")
        return phone


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش'),
    )
    name = forms.CharField(max_length=100, required=True, label='نام', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(max_length=100, required=True, label='ایمیل', widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone = forms.CharField(max_length=11, required=True, label='شماره تماس', widget=forms.TextInput(attrs={'class': 'form-control'}))
    message = forms.CharField(max_length=500, required=True, label='پیام', widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}))
    subject = forms.ChoiceField(label='موضوع', choices=SUBJECT_CHOICES)

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError("شماره تلفن عددی نیست")
            else:
                return phone


class CreatePostForm(forms.ModelForm):
    image1 = forms.ImageField(label="تصویر اول", widget=forms.FileInput(attrs={'class': 'form-control'}))
    image2 = forms.ImageField(label="تصویر دوم", widget=forms.FileInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Post
        fields = ['description', 'tags']
        widgets = {
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
        }
        labels = {
            'tags': 'تگ ها',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        widgets = {
            'body': forms.TextInput(attrs={'placeholder': 'کامنت بزارید...', 'class': 'form-control input-sm'}),
        }


class SearchForm(forms.Form):
    query = forms.CharField()

social/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (PasswordChangeView, PasswordChangeDoneView, PasswordResetView,
                                       PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView)
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count, Q
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from taggit.models import Tag
from .forms import *
from .models import Post, Contact, Image


def profile(request):
    try:
        user = User.objects.prefetch_related('followers', 'following').get(id=request.user.id)
    except:
        return redirect('social:login')
    saved_posts = user.saved_posts.all()[:7]
    my_posts = user.user_posts.all()[:8]
    following = user.get_followings()
    followers = user.get_followers()
    conntext = {
        'saved_posts': saved_posts,
        'my_posts': my_posts,
        'user': user,
        'following': following,
        'followers': followers,
        'form': CommentForm()
    }
    return render(request, 'social/profile.html', conntext)


def user_register(request):
    if request.user.is_authenticated:
        return redirect('social:profile')
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            messages.success(request, 'با موفقیت ثبت نام کردی', 'success')
            return redirect('social:profile')
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required
def user_edit(request):
    if request.method == 'POST':
        form = UserEditForm(data=request.POST, files=request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('social:profile')
    else:
        form = UserEditForm(instance=request.user)
    return render(request, 'registration/edit_user.html', {'form': form})


def user_login(request):
    if request.user.is_authenticated:
        return redirect('social:profile')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.success(request, 'با موفقیت لاگین شدی', 'success')
                    return redirect('social:profile')
                else:
                    messages.error(request, 'این کاربر فعال نیست', 'danger')
                    return redirect('social:login')
            else:
                messages.error(request, 'نام کاربری یا رمز عبور اشتباه هست', 'danger')
                return redirect('social:login')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})


@login_required
def user_logout(request):
    if request.method == 'POST':
        logout(request)
        return redirect('social:profile')
    return render(request, 'registration/logged_out.html')


@login_required
def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            message = f"{cd['name']}\n{cd['email']}\n{cd['phone']}\n\n{cd['message']}"
            send_mail(cd['subject'], message, 'danielsadri01@gmail.com', ['danielsadri01@gmail.com'], False)
            messages.success(request, 'پیام شما به پشتبانی ارسال شد', 'success')
            return redirect('social:profile')
    else:
        form = TicketForm()
    return render(request, 'forms/ticket.html', {'form': form})


class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'registration/password_change_form.html'
    success_url = reverse_lazy('social:password_change_done')


class CustomPasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'registration/password_change_done.html'


class CustomPasswordResetView(PasswordResetView):
    template_name = 'registration/password_reset_form.html'
    email_template_name = 'registration/password_reset_email.html'
    success_url = reverse_lazy('social:password_reset_done')


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'registration/password_reset_done.html'


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'registration/password_reset_confirm.html'
    success_url = reverse_lazy('social:password_reset_complete')


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'registration/password_reset_complete.html'


def post_list(request, tag_slug=None):
    posts = Post.objects.select_related('author').order_by('-total_likes')
    latest_users = User.objects.filter(is_active=True).order_by('-date_joined')[:4]
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = Post.objects.filter(tags__in=[tag])
    page = request.GET.get('page')
    paginator = Paginator(posts, 2)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = []
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return render(request, 'social/list_ajax.html', {'posts': posts})
    context = {
        'posts': posts,
        'tag': tag,
        'latest_users': latest_users,
    }
    return render(request, "social/list.html", context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_post = Post.objects.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_post = similar_post.annotate(same_tags=Count('tags')).order_by('-same_tags', '-created')[:4]
    context = {
        'post': post,
        'similar_post': similar_post,
        'form': CommentForm()
    }
    return render(request, "social/detail.html", context)


@login_required
def post_create(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            form.save_m2m()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('social:profile')
    else:
        form = CreatePostForm()
    return render(request, 'forms/create-post.html', {'form': form})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.name = request.user.first_name
        comment.save()
    return redirect('social:profile')


def post_search(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data.get('query')
            results = Post.objects.filter(Q(description__icontains=query))
    context = {
        'results': results,
        'query': query
    }
    return render(request, 'social/search.html', context)


@login_required
@require_POST
def like_post(request):
    post_id = request.POST.get('post_id')
    if post_id is not None:
        post = get_object_or_404(Post, id=post_id)
        user = request.user
        if user in post.likes.all():
            post.likes.remove(user)
            liked = False
        else:
            post.likes.add(user)
            liked = True
        post_likes_count = post.likes.count()
        response_data = {'liked': liked, 'likes_count': post_likes_count}
    else:
        response_data = {'error': 'Invalid post_id'}
    return JsonResponse(response_data)


@login_required
@require_POST
def save_post(request):
    post_id = request.POST.get('post_id')
    if post_id is not None:
        post = get_object_or_404(Post, id=post_id)
        user = request.user
        if user in post.saved_by.all():
            post.saved_by.remove(user)
            saved = False
        else:
            post.saved_by.add(user)
            saved = True
        response_data = {'saved': saved}
    else:
        response_data = {'error': 'Invalid request'}
    return JsonResponse(response_data)


@login_required
def user_list(request):
    users = User.objects.filter(is_active=True)
    return render(request, 'user/user_list.html', {'users': users})


@login_required
def user_detail(request, username):
    user = get_object_or_404(User, username=username, is_active=True)
    return render(request, 'user/user_detail.html', {'user': user})


@login_required
@require_POST
def user_follow(request):
    user_id = request.POST.get('id')
    if user_id:
        try:
            user = User.objects.get(id=user_id)
            if request.user in user.followers.all():
                Contact.objects.filter(user_from=request.user, user_to=user).delete()
                follow = False
            else:
                Contact.objects.get_or_create(user_from=request.user, user_to=user)
                follow = True
            following_count = user.following.count()
            followers_count = user.followers.count()

social/templates/social/detail.html
{% extends 'parent/base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %} post detail {% endblock %}


{% block content %}
    <section class="single-post">
        <div class="container">
            <div class="row">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-md-8 modal-image">
                                    <img class="img-responsive" src="{{ post.images.first.image_file.url }}" alt="Image"/>
                                    <br>
                                    <div class="text-center"><p class="text-dark">{{ post.description }}</p></div>
                                    <br>
                                    <div class="text-center">
                                        {% for tag in post.tags.all %}
                                            <a class="text-dark" href="{% url 'social:post_list_by_tag' tag.slug %}"><button> {{ tag.name }}</button></a>
                                            {% if not forloop.last %}, {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>
                                <div class="col-md-4 modal-meta">
                                    <div class="modal-meta-top">
                                        <div class="img-poster clearfix">
                                            <a href="#"><img class="img-responsive img-circle" src="{{ post.author.photo.url }}" alt="Image"/></a>
                                            <span>{{ post.created|date:"Y/m/d-H:i" }}</span><br/>
                                            <strong><a href="#">{{ post.author.get_full_name }}</a></strong>
                                            <button id="save-post" class="kafe-btn kafe-btn-danger-small">
                                                {% if user in post.saved_by.all %}
                                                    حذف از ذخیره
                                                {% else %}
                                                    ذخیره پست
                                                {% endif %}
                                            </button>
                                        </div>
                                        <ul class="img-comment-list">
                                            {% for comment in post.comments.all %}
                                                <li>
                                                    <div class="comment-img">
                                                        <img src="{% static 'images/profile/avatar2.png' %}" class="img-responsive img-circle" alt="Image"/>
                                                    </div>
                                                    <div class="comment-text">
                                                        <strong><a href="#">{{ comment.name }}</a></strong>
                                                        <p class="">{{ comment.body }}</p> <span class="date sub-text"> در {{ comment.created }} </span>
                                                    </div>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                        <div class="modal-meta-bottom">
                                            <ul>
                                                <li>
                                                    <a class="modal-like" href="#">
                                                        {% if request.user in post.likes.all %}
                                                            <i class="fa fa-heart" id="like-button"> UnLike </i>
                                                        {% else %}
                                                            <i class="fa fa-heartbeat" id="like-button"> like </i>
                                                        {% endif %}
                                                    </a>
                                                    <span class="modal-one" id="likes-count"> {{ post.total_likes }}</span> |
                                                    <a class="modal-comment" href="#"><i class="fa fa-comments"></i></a><span>{{ post.comments.count }}</span>
                                                </li>
                                                <li>
											<span class="thumb-xs">
												<img class="img-responsive img-circle" src="{% static 'images/profile/avatar2.webp' %}" alt="Image">
											</span>
                                                    <div class="comment-body">
                                                        <form method="post" action="{% url 'social:post_comment' post.id %}">
                                                            {% csrf_token %}
                                                            {{ form.as_p }}
                                                            <div class="col-12"><button type="submit" class="btn btn-dark">ثبت</button></div>
                                                        </form>
                                                    </div>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="row top-row">
        <div class="text-center"><h3 class="text-dark">پست های مشابه</h3></div>
        <br><br><br>
        {% for s_post in similar_post %}
            <div class="col-lg-3">
                <div class="tr-section">
                    <div class="tr-post">
                        <div class="entry-header">
                            <div class="entry-thumbnail">
                                <a href="{% url 'social:post_detail' s_post.id %}">
                                    <img class="img-fluid" src="{{ s_post.images.first.image_file.url }}" alt="Image">
                                </a>
                            </div>
                        </div>
                        <div class="post-content">
                            <div class="author-post text-center">
                                <a href="{% url 'social:user_detail' s_post.author.username %}">
                                    {% if user.photo %}
                                        <img class="img-fluid rounded-circle" src="{{ s_post.author.photo.url }}" alt="Image"></a>
                                    {% else %}
                                        <img class="img-fluid rounded-circle" src="{% static 'images/profile/Avatar.png' %}" alt="Image">
                                    {% endif %}
                            </div>
                            <div class="card-content">
                                <h4>{{ s_post.author.get_full_name }}</h4><span>{{ s_post.author.username }}</span>
                            </div>
                            <a href="{% url 'social:post_detail' s_post.id %}" class="kafe-btn kafe-btn-mint-small full-width">مشاهده</a>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="text-center"> هیچ پست مشابهی وجود ندارد</div>
        {% endfor %}
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
            integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        $(document).ready(function () {
            $('#like-button').click(function () {
                var button = $(this);
                $.ajax({
                    type: 'POST',
                    url: '{% url 'social:like_post' %}',
                    data: {'post_id': {{post.id}}, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                    success: function (data) {
                        if (data.liked) {
                            button.text('UnLike');
                            button.removeClass('fa-heartbeat');
                            button.addClass('fa-heart')
                        } else {
                            button.text('Like');
                            button.removeClass('fa-heart');
                            button.addClass('fa-heartbeat')
                        }
                        $('#likes-count').text(data.likes_count);
                    },
                });
            });
            $("#save-post").click(function () {
                var button = $(this);
                $.ajax({
                    type: "POST",
                    url: '{% url 'social:save_post' %}',
                    data: {'csrfmiddlewaretoken': '{{ csrf_token }}', 'post_id': {{post.id}}},
                    success: function (data) {
                        if (data.saved) {
                            button.text("حذف از ذخیره");
                        } else {
                            button.text("ذخیره پست");
                        }
                    },
                    error: function (error) {
                        console.log("خطا در ارسال درخواست Ajax: " + error);
                    }
                });
            });
        });
    </script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>
    <script src="{% static 'plugins/slimscroll/jquery.slimscroll.js' %}"></script>
    <script>
        $('#Slim,#Slim2').slimScroll({
            height: "auto",
            position: 'right',
            railVisible: true,
            alwaysVisible: true,
            size: "8px",
        });
    </script>
{% endblock %}

social/templates/social/list_ajax.html
<div class="row">
    {% if posts %}
        <br>
        <br>
    {% endif %}
    {% for post in posts %}
        <div class="col-lg-4 m-4">
            <a href="{{ post.get_absolute_url }}" data-toggle="modal">
                <div class="explorebox" style="background: linear-gradient( rgba(34,34,34,0.2), rgba(34,34,34,0.2)), url('{{ post.images.first.image_file.url }}') no-repeat;
                             background-size: cover;
                             background-position: center center;
                             -webkit-background-size: cover;
                             -moz-background-size: cover;
                             -o-background-size: cover;">
                    <div class="explore-top">
                        <div class="explore-like"><i class="fa fa-heart"></i> <span>{{ post.total_likes }}</span></div>
                        <div class="explore-circle pull-left"><span>{{ post.total_saves }}&nbsp;</span><i class="far fa-bookmark"></i></div>
                    </div>
                    <div class="explore-body">
                        <div class="">
                            <img class="img-circle" src="{{ post.author.photo.url }}" alt="user">
                        </div>
                    </div>
                </div>
            </a>
            <h6 class="">{{ post.created|date:"Y/m/d-H:i" }}</h6>
            {% for tag in post.tags.all %}
                <a class="text-dark" href="{% url 'social:post_list_by_tag' tag.slug %}">
                    <button> {{ tag.name }}</button>
                </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </div>
    {% endfor %}
</div>